//To Create and Insert Documents(Data) into Attendance Collection(Table)//

db.attendance.insertMany([
    { userID:'UID001', topicID:'TPC001' , status: 'Present' },
    { userID:'UID002', topicID:'TPC001' , status: 'Present' },
    { userID:'UID003', topicID:'TPC001' , status: 'Present' },
    { userID:'UID004', topicID:'TPC001' , status: 'Present' },
    { userID:'UID005', topicID:'TPC001' , status: 'Present' },
    { userID:'UID006', topicID:'TPC001' , status: 'Present' },
    { userID:'UID007', topicID:'TPC001' , status: 'Present' },
    { userID:'UID008', topicID:'TPC001' , status: 'Present' },
    { userID:'UID009', topicID:'TPC001' , status: 'Present' },
    { userID:'UID010', topicID:'TPC001' , status: 'Present' },
  
    { userID:'UID001', topicID:'TPC002' , status: 'Present' },
    { userID:'UID002', topicID:'TPC002' , status: 'Present' },
    { userID:'UID003', topicID:'TPC002' , status: 'Present' },
    { userID:'UID004', topicID:'TPC002' , status: 'Present' },
    { userID:'UID005', topicID:'TPC002' , status: 'Present' },
    { userID:'UID006', topicID:'TPC002' , status: 'Present' },
    { userID:'UID007', topicID:'TPC002' , status: 'Present' },
    { userID:'UID008', topicID:'TPC002' , status: 'Present' },
    { userID:'UID009', topicID:'TPC002' , status: 'Absent' },
    { userID:'UID010', topicID:'TPC002' , status: 'Absent' },
  
    { userID:'UID001', topicID:'TPC003' , status: 'Present' },
    { userID:'UID002', topicID:'TPC003' , status: 'Present' },
    { userID:'UID003', topicID:'TPC003' , status: 'Present' },
    { userID:'UID004', topicID:'TPC003' , status: 'Present' },
    { userID:'UID005', topicID:'TPC003' , status: 'Present' },
    { userID:'UID006', topicID:'TPC003' , status: 'Present' },
    { userID:'UID007', topicID:'TPC003' , status: 'Absent' },
    { userID:'UID008', topicID:'TPC003' , status: 'Absent' },
    { userID:'UID009', topicID:'TPC003' , status: 'Present' },
    { userID:'UID010', topicID:'TPC003' , status: 'Present' },
  
    { userID:'UID001', topicID:'TPC004' , status: 'Present' },
    { userID:'UID002', topicID:'TPC004' , status: 'Present' },
    { userID:'UID003', topicID:'TPC004' , status: 'Present' },
    { userID:'UID004', topicID:'TPC004' , status: 'Absent' },
    { userID:'UID005', topicID:'TPC004' , status: 'Absent' },
    { userID:'UID006', topicID:'TPC004' , status: 'Present' },
    { userID:'UID007', topicID:'TPC004' , status: 'Present' },
    { userID:'UID008', topicID:'TPC004' , status: 'Present' },
    { userID:'UID009', topicID:'TPC004' , status: 'Present' },
    { userID:'UID010', topicID:'TPC004' , status: 'Present' },
  
    { userID:'UID001', topicID:'TPC005' , status: 'Present' },
    { userID:'UID002', topicID:'TPC005' , status: 'Present' },
    { userID:'UID003', topicID:'TPC005' , status: 'Present' },
    { userID:'UID004', topicID:'TPC005' , status: 'Present' },
    { userID:'UID005', topicID:'TPC005' , status: 'Present' },
    { userID:'UID006', topicID:'TPC005' , status: 'Present' },
    { userID:'UID007', topicID:'TPC005' , status: 'Present' },
    { userID:'UID008', topicID:'TPC005' , status: 'Present' },
    { userID:'UID009', topicID:'TPC005' , status: 'Present' },
    { userID:'UID010', topicID:'TPC005' , status: 'Present' },
  
    { userID:'UID001', topicID:'TPC006' , status: 'Present' },
    { userID:'UID002', topicID:'TPC006' , status: 'Absent' },
    { userID:'UID003', topicID:'TPC006' , status: 'Absent' },
    { userID:'UID004', topicID:'TPC006' , status: 'Present' },
    { userID:'UID005', topicID:'TPC006' , status: 'Present' },
    { userID:'UID006', topicID:'TPC006' , status: 'Present' },
    { userID:'UID007', topicID:'TPC006' , status: 'Present' },
    { userID:'UID008', topicID:'TPC006' , status: 'Present' },
    { userID:'UID009', topicID:'TPC006' , status: 'Present' },
    { userID:'UID010', topicID:'TPC006' , status: 'Present' },
  
    { userID:'UID001', topicID:'TPC007' , status: 'Present' },
    { userID:'UID002', topicID:'TPC007' , status: 'Present' },
    { userID:'UID003', topicID:'TPC007' , status: 'Present' },
    { userID:'UID004', topicID:'TPC007' , status: 'Present' },
    { userID:'UID005', topicID:'TPC007' , status: 'Absent' },
    { userID:'UID006', topicID:'TPC007' , status: 'Present' },
    { userID:'UID007', topicID:'TPC007' , status: 'Present' },
    { userID:'UID008', topicID:'TPC007' , status: 'Present' },
    { userID:'UID009', topicID:'TPC007' , status: 'Present' },
    { userID:'UID010', topicID:'TPC007' , status: 'Present' },
  
    { userID:'UID001', topicID:'TPC008' , status: 'Absent' },
    { userID:'UID002', topicID:'TPC008' , status: 'Absent' },
    { userID:'UID003', topicID:'TPC008' , status: 'Absent' },
    { userID:'UID004', topicID:'TPC008' , status: 'Absent' },
    { userID:'UID005', topicID:'TPC008' , status: 'Absent' },
    { userID:'UID006', topicID:'TPC008' , status: 'Absent' },
    { userID:'UID007', topicID:'TPC008' , status: 'Absent' },
    { userID:'UID008', topicID:'TPC008' , status: 'Absent' },
    { userID:'UID009', topicID:'TPC008' , status: 'Absent' },
    { userID:'UID010', topicID:'TPC008' , status: 'Absent' },
  
    { userID:'UID001', topicID:'TPC009' , status: 'Present' },
    { userID:'UID002', topicID:'TPC009' , status: 'Present' },
    { userID:'UID003', topicID:'TPC009' , status: 'Present' },
    { userID:'UID004', topicID:'TPC009' , status: 'Present' },
    { userID:'UID005', topicID:'TPC009' , status: 'Present' },
    { userID:'UID006', topicID:'TPC009' , status: 'Present' },
    { userID:'UID007', topicID:'TPC009' , status: 'Absent' },
    { userID:'UID008', topicID:'TPC009' , status: 'Present' },
    { userID:'UID009', topicID:'TPC009' , status: 'Present' },
    { userID:'UID010', topicID:'TPC009' , status: 'Absent' },
  
    { userID:'UID001', topicID:'TPC010' , status: 'Present' },
    { userID:'UID002', topicID:'TPC010' , status: 'Present' },
    { userID:'UID003', topicID:'TPC010' , status: 'Present' },
    { userID:'UID004', topicID:'TPC010' , status: 'Present' },
    { userID:'UID005', topicID:'TPC010' , status: 'Present' },
    { userID:'UID006', topicID:'TPC010' , status: 'Present' },
    { userID:'UID007', topicID:'TPC010' , status: 'Present' },
    { userID:'UID008', topicID:'TPC010' , status: 'Present' },
    { userID:'UID009', topicID:'TPC010' , status: 'Present' },
    { userID:'UID010', topicID:'TPC010' , status: 'Present' },
  ])